/**
 * N2 Wheels — regenerate the fitment-only Supabase sync patch.
 *
 * WHY: on the live site the product detail pages HYDRATE from the database
 * (`useLiveProduct` swaps the sample row for the `public.products` row once a
 * Supabase read succeeds), and the "Will this fit my car?" verdict then reads
 * `row.fitment` — mapped by `fitmentRecords()` in src/lib/store.ts. So shipping
 * richer sample fitment records in src/data/products.ts only changes the live
 * product pages once the matching rows in `public.products` carry them too.
 *
 * This emits a TARGETED, idempotent patch: it updates ONLY the `fitment` jsonb
 * (and `updated_at`) of the products that have sample fitment data. Prices,
 * stock, specs, images and descriptions are untouched — no owner-entered or
 * imported catalogue data is overwritten.
 *
 * Usage:  bun ./scripts/gen-fitment-sync-sql.ts > scripts/sync-fitment-records.sql
 */
import { demoPackages, demoWheels } from "../src/data/products";

interface FitmentRow {
  id: string;
  category: string;
  compatibility: string[];
  fitments: unknown[];
}

const rows: FitmentRow[] = [
  ...demoWheels.map((w) => ({
    id: w.id,
    category: "wheels",
    compatibility: w.vehicleCompatibility,
    fitments: w.vehicleFitments ?? [],
  })),
  ...demoPackages.map((p) => ({
    id: p.id,
    category: "packages",
    compatibility: [],
    fitments: p.vehicleFitments ?? [],
  })),
].filter((r) => r.fitments.length > 0);

/** Single-quoted SQL literal (the jsonb payload never contains a quote we must escape twice). */
const lit = (s: string): string => `'${s.replace(/'/g, "''")}'`;

const lines: string[] = [
  "-- N2 Wheels — fitment-only sync patch for public.products.",
  "--",
  "-- Generated by: bun ./scripts/gen-fitment-sync-sql.ts > scripts/sync-fitment-records.sql",
  "-- Safe to re-run (idempotent). Touches ONLY the fitment jsonb + updated_at.",
  "-- Run as the owner (or in the Supabase SQL editor): anon can read products but",
  "-- cannot update them — RLS grants products writes to the `authenticated` role only.",
  "",
  "begin;",
  "",
];

for (const r of rows) {
  const payload = JSON.stringify({ compatibility: r.compatibility, fitments: r.fitments });
  lines.push(
    `-- ${r.category}: ${r.fitments.length} sample fitment record(s)`,
    `update public.products`,
    `   set fitment = ${lit(payload)}::jsonb,`,
    `       updated_at = now()`,
    ` where id = ${lit(r.id)};`,
    "",
  );
}

lines.push(
  "-- Verify (expect the same record counts you just wrote):",
  ...rows.map(
    (r) =>
      `--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = ${lit(r.id)};`,
  ),
  "",
  "commit;",
  "",
);

console.log(lines.join("\n"));
