-- N2 Wheels — fitment-only sync patch for public.products.
--
-- Generated by: bun ./scripts/gen-fitment-sync-sql.ts > scripts/sync-fitment-records.sql
-- Safe to re-run (idempotent). Touches ONLY the fitment jsonb + updated_at.
-- Run as the owner (or in the Supabase SQL editor): anon can read products but
-- cannot update them — RLS grants products writes to the `authenticated` role only.

begin;

-- wheels: 39 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":["Audi","BMW","Mercedes-Benz","Volkswagen"],"fitments":[{"make":"BMW","model":"3 Series","generation":"F30","yearsStart":2012,"yearsEnd":2018},{"make":"Volkswagen","model":"Golf","generation":"MK7","yearsStart":2013,"yearsEnd":2020},{"make":"Audi","model":"A3"},{"make":"Audi","model":"A4"},{"make":"Audi","model":"A5"},{"make":"Audi","model":"A6"},{"make":"Audi","model":"S3"},{"make":"Audi","model":"S4"},{"make":"Audi","model":"S5"},{"make":"Audi","model":"Q3"},{"make":"Audi","model":"Q5"},{"make":"BMW","model":"1 Series"},{"make":"BMW","model":"2 Series"},{"make":"BMW","model":"4 Series"},{"make":"BMW","model":"5 Series"},{"make":"BMW","model":"X1"},{"make":"BMW","model":"X2"},{"make":"BMW","model":"X3"},{"make":"BMW","model":"X4"},{"make":"BMW","model":"X5"},{"make":"BMW","model":"M3"},{"make":"BMW","model":"M4"},{"make":"Mercedes-Benz","model":"A-Class"},{"make":"Mercedes-Benz","model":"A180"},{"make":"Mercedes-Benz","model":"A200"},{"make":"Mercedes-Benz","model":"A45"},{"make":"Mercedes-Benz","model":"C-Class"},{"make":"Mercedes-Benz","model":"C180"},{"make":"Mercedes-Benz","model":"C200"},{"make":"Mercedes-Benz","model":"C63"},{"make":"Mercedes-Benz","model":"E200"},{"make":"Mercedes-Benz","model":"GLA"},{"make":"Mercedes-Benz","model":"GLC"},{"make":"Mercedes-Benz","model":"GLE"},{"make":"Volkswagen","model":"Golf R"},{"make":"Volkswagen","model":"Passat"},{"make":"Volkswagen","model":"Tiguan"},{"make":"Volkswagen","model":"T-Roc"},{"make":"Volkswagen","model":"Arteon"}]}'::jsonb,
       updated_at = now()
 where id = 'w-forza-r1-18';

-- wheels: 46 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":["Audi","BMW","Mercedes-Benz","Volkswagen","Nissan","Toyota","Honda"],"fitments":[{"make":"Nissan","model":"Qashqai","generation":"J11","yearsStart":2014,"yearsEnd":2021},{"make":"Toyota","model":"Corolla","generation":"E210","yearsStart":2019,"yearsEnd":2022},{"make":"Audi","model":"A3"},{"make":"Audi","model":"A4"},{"make":"Audi","model":"A5"},{"make":"Audi","model":"S3"},{"make":"Audi","model":"S4"},{"make":"Audi","model":"Q3"},{"make":"Audi","model":"Q5"},{"make":"BMW","model":"1 Series"},{"make":"BMW","model":"2 Series"},{"make":"BMW","model":"3 Series"},{"make":"BMW","model":"4 Series"},{"make":"BMW","model":"5 Series"},{"make":"BMW","model":"X1"},{"make":"BMW","model":"X2"},{"make":"BMW","model":"X3"},{"make":"BMW","model":"X4"},{"make":"BMW","model":"X5"},{"make":"BMW","model":"M3"},{"make":"BMW","model":"M4"},{"make":"Mercedes-Benz","model":"A-Class"},{"make":"Mercedes-Benz","model":"A180"},{"make":"Mercedes-Benz","model":"A200"},{"make":"Mercedes-Benz","model":"A45"},{"make":"Mercedes-Benz","model":"C-Class"},{"make":"Mercedes-Benz","model":"C180"},{"make":"Mercedes-Benz","model":"C200"},{"make":"Mercedes-Benz","model":"C63"},{"make":"Mercedes-Benz","model":"GLA"},{"make":"Mercedes-Benz","model":"GLC"},{"make":"Volkswagen","model":"Golf"},{"make":"Volkswagen","model":"Golf R"},{"make":"Volkswagen","model":"Passat"},{"make":"Volkswagen","model":"Tiguan"},{"make":"Volkswagen","model":"T-Roc"},{"make":"Volkswagen","model":"Arteon"},{"make":"Nissan","model":"Micra"},{"make":"Nissan","model":"Juke"},{"make":"Nissan","model":"X-Trail"},{"make":"Nissan","model":"Leaf"},{"make":"Nissan","model":"Ariya"},{"make":"Toyota","model":"RAV4"},{"make":"Toyota","model":"C-HR"},{"make":"Toyota","model":"Camry"},{"make":"Toyota","model":"Supra"}]}'::jsonb,
       updated_at = now()
 where id = 'w-vortex-vx9-19';

-- wheels: 1 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":["Subaru","Volkswagen","Seat"],"fitments":[{"make":"Volkswagen","model":"Golf","generation":"MK4","yearsStart":1998,"yearsEnd":2003}]}'::jsonb,
       updated_at = now()
 where id = 'w-apex-a7-18';

-- wheels: 1 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":["Ford","Volvo","Vauxhall"],"fitments":[{"make":"Ford","model":"Focus","generation":"MK3","yearsStart":2011,"yearsEnd":2018}]}'::jsonb,
       updated_at = now()
 where id = 'w-drifter-d5-17';

-- wheels: 13 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":["Audi","Mercedes-Benz","Volkswagen"],"fitments":[{"make":"Audi","model":"A4"},{"make":"Audi","model":"A5"},{"make":"Audi","model":"A6"},{"make":"Audi","model":"Q3"},{"make":"Audi","model":"Q5"},{"make":"Mercedes-Benz","model":"A-Class"},{"make":"Mercedes-Benz","model":"C-Class"},{"make":"Mercedes-Benz","model":"E200"},{"make":"Mercedes-Benz","model":"GLC"},{"make":"Volkswagen","model":"Golf"},{"make":"Volkswagen","model":"Passat"},{"make":"Volkswagen","model":"Tiguan"},{"make":"Volkswagen","model":"Arteon"}]}'::jsonb,
       updated_at = now()
 where id = 'w-turbo-t6-19';

-- wheels: 4 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":["Ford","Toyota","Vauxhall"],"fitments":[{"make":"Ford","model":"Fiesta","generation":"MK7","yearsStart":2008,"yearsEnd":2017},{"make":"Toyota","model":"Yaris","generation":"XP130","yearsStart":2011,"yearsEnd":2020},{"make":"Toyota","model":"Aygo","generation":"AB10","yearsStart":2014,"yearsEnd":2022},{"make":"Vauxhall","model":"Corsa","generation":"D","yearsStart":2006,"yearsEnd":2014}]}'::jsonb,
       updated_at = now()
 where id = 'w-grip-g9-16';

-- packages: 23 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":[],"fitments":[{"make":"BMW","model":"3 Series","generation":"F30","yearsStart":2012,"yearsEnd":2018},{"make":"Volkswagen","model":"Golf","generation":"MK7","yearsStart":2013,"yearsEnd":2020},{"make":"Audi","model":"A3"},{"make":"Audi","model":"A4"},{"make":"Audi","model":"A5"},{"make":"Audi","model":"S3"},{"make":"Audi","model":"Q5"},{"make":"BMW","model":"1 Series"},{"make":"BMW","model":"2 Series"},{"make":"BMW","model":"4 Series"},{"make":"BMW","model":"5 Series"},{"make":"BMW","model":"X1"},{"make":"BMW","model":"X3"},{"make":"BMW","model":"M4"},{"make":"Mercedes-Benz","model":"A-Class"},{"make":"Mercedes-Benz","model":"A180"},{"make":"Mercedes-Benz","model":"C-Class"},{"make":"Mercedes-Benz","model":"GLA"},{"make":"Mercedes-Benz","model":"GLC"},{"make":"Volkswagen","model":"Golf R"},{"make":"Volkswagen","model":"Passat"},{"make":"Volkswagen","model":"Tiguan"},{"make":"Volkswagen","model":"T-Roc"}]}'::jsonb,
       updated_at = now()
 where id = 'pkg-track-day';

-- packages: 2 sample fitment record(s)
update public.products
   set fitment = '{"compatibility":[],"fitments":[{"make":"Ford","model":"Fiesta","generation":"MK7","yearsStart":2008,"yearsEnd":2017},{"make":"Vauxhall","model":"Corsa","generation":"D","yearsStart":2006,"yearsEnd":2014}]}'::jsonb,
       updated_at = now()
 where id = 'pkg-street-pro';

-- Verify (expect the same record counts you just wrote):
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'w-forza-r1-18';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'w-vortex-vx9-19';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'w-apex-a7-18';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'w-drifter-d5-17';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'w-turbo-t6-19';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'w-grip-g9-16';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'pkg-track-day';
--   select id, jsonb_array_length(fitment->'fitments') as records from public.products where id = 'pkg-street-pro';

commit;

